### ISSUE TITLE
2nd Argument Provided to `trackerService.emit` Ignored

### ISSUE THREAD

**Issue by carloferrer** [jrmykolyn/test.js.tracker#1]
Providing a `payload` to `trackerService.emit` doesn't do much with respect to altering the returned object; it seems like `payload` is ignored entirely.
https://github.com/jrmykolyn/test.js.tracker/blob/74b2dba8cfb031d848cd86ebf7a0fb33051aa68e/demo/index.js#L23

**Comment by jrmykolyn** [comment]
Good flag! I'll update the example client to make it more clear that the event `payload` is actually available for use by each handler, augmenter, etc.

**Comment by jrmykolyn** [comment]
@carloferrer This has been addressed via #2, which updates the `augmenter` functions so that they make use of the event data.

To preview this functionality, navigate to the root of the repository and run the following command:

```
node demo/index.js
```
